name: linter

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]

jobs:
  linter:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbt-labs/dbt-snowflake:1.8.3

    steps:
      - name: Checkout code repository in agent
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      - name: Set ownership
        run: |
          chown -R $(id -u):$(id -g) $PWD

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake sqlfluff sqlfluff-templater-dbt black

      - name: Run linting checks
        run: |
          bash ./bin/linter.sh
